-- H5.41 - Sincronização offline, versionamento e colunas JSON geradas
-- Rode após 012. Script defensivo para HostGator/MySQL/MariaDB.

CREATE TABLE IF NOT EXISTS sync_actions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  client_uuid VARCHAR(80) NULL,
  tabela VARCHAR(80) NOT NULL,
  entidade_id VARCHAR(80) NULL,
  operacao VARCHAR(20) NOT NULL,
  status VARCHAR(30) NOT NULL,
  usuario_id VARCHAR(64) NULL,
  payload LONGTEXT NULL,
  criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_sync_uuid (client_uuid),
  INDEX idx_sync_status (status),
  INDEX idx_sync_entidade (tabela, entidade_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET @db := DATABASE();

-- Colunas de sync/optimistic locking nas tabelas operacionais.
SET @tables := 'viagens,veiculos,pacientes,passageiros,despesas,ocorrencias,alertas,mensagens,checklists,eventos,localizacoes,destinos';

-- viagens
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='viagens' AND COLUMN_NAME='client_uuid')=0,
  'ALTER TABLE viagens ADD COLUMN client_uuid VARCHAR(80) NULL', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='viagens' AND COLUMN_NAME='client_timestamp')=0,
  'ALTER TABLE viagens ADD COLUMN client_timestamp DATETIME NULL', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='viagens' AND COLUMN_NAME='version')=0,
  'ALTER TABLE viagens ADD COLUMN version INT UNSIGNED NOT NULL DEFAULT 1', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- veiculos
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='veiculos' AND COLUMN_NAME='client_uuid')=0,
  'ALTER TABLE veiculos ADD COLUMN client_uuid VARCHAR(80) NULL', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='veiculos' AND COLUMN_NAME='client_timestamp')=0,
  'ALTER TABLE veiculos ADD COLUMN client_timestamp DATETIME NULL', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='veiculos' AND COLUMN_NAME='version')=0,
  'ALTER TABLE veiculos ADD COLUMN version INT UNSIGNED NOT NULL DEFAULT 1', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- pacientes
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='pacientes' AND COLUMN_NAME='client_uuid')=0,
  'ALTER TABLE pacientes ADD COLUMN client_uuid VARCHAR(80) NULL', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='pacientes' AND COLUMN_NAME='client_timestamp')=0,
  'ALTER TABLE pacientes ADD COLUMN client_timestamp DATETIME NULL', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='pacientes' AND COLUMN_NAME='version')=0,
  'ALTER TABLE pacientes ADD COLUMN version INT UNSIGNED NOT NULL DEFAULT 1', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- passageiros
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='passageiros' AND COLUMN_NAME='client_uuid')=0,
  'ALTER TABLE passageiros ADD COLUMN client_uuid VARCHAR(80) NULL', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='passageiros' AND COLUMN_NAME='client_timestamp')=0,
  'ALTER TABLE passageiros ADD COLUMN client_timestamp DATETIME NULL', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='passageiros' AND COLUMN_NAME='version')=0,
  'ALTER TABLE passageiros ADD COLUMN version INT UNSIGNED NOT NULL DEFAULT 1', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- despesas
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='despesas' AND COLUMN_NAME='client_uuid')=0,
  'ALTER TABLE despesas ADD COLUMN client_uuid VARCHAR(80) NULL', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='despesas' AND COLUMN_NAME='client_timestamp')=0,
  'ALTER TABLE despesas ADD COLUMN client_timestamp DATETIME NULL', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='despesas' AND COLUMN_NAME='version')=0,
  'ALTER TABLE despesas ADD COLUMN version INT UNSIGNED NOT NULL DEFAULT 1', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- ocorrencias
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='ocorrencias' AND COLUMN_NAME='client_uuid')=0,
  'ALTER TABLE ocorrencias ADD COLUMN client_uuid VARCHAR(80) NULL', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='ocorrencias' AND COLUMN_NAME='client_timestamp')=0,
  'ALTER TABLE ocorrencias ADD COLUMN client_timestamp DATETIME NULL', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='ocorrencias' AND COLUMN_NAME='version')=0,
  'ALTER TABLE ocorrencias ADD COLUMN version INT UNSIGNED NOT NULL DEFAULT 1', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- alertas
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='alertas' AND COLUMN_NAME='client_uuid')=0,
  'ALTER TABLE alertas ADD COLUMN client_uuid VARCHAR(80) NULL', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='alertas' AND COLUMN_NAME='client_timestamp')=0,
  'ALTER TABLE alertas ADD COLUMN client_timestamp DATETIME NULL', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='alertas' AND COLUMN_NAME='version')=0,
  'ALTER TABLE alertas ADD COLUMN version INT UNSIGNED NOT NULL DEFAULT 1', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- mensagens
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='mensagens' AND COLUMN_NAME='client_uuid')=0,
  'ALTER TABLE mensagens ADD COLUMN client_uuid VARCHAR(80) NULL', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='mensagens' AND COLUMN_NAME='client_timestamp')=0,
  'ALTER TABLE mensagens ADD COLUMN client_timestamp DATETIME NULL', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='mensagens' AND COLUMN_NAME='version')=0,
  'ALTER TABLE mensagens ADD COLUMN version INT UNSIGNED NOT NULL DEFAULT 1', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- checklists
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='checklists' AND COLUMN_NAME='client_uuid')=0,
  'ALTER TABLE checklists ADD COLUMN client_uuid VARCHAR(80) NULL', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='checklists' AND COLUMN_NAME='client_timestamp')=0,
  'ALTER TABLE checklists ADD COLUMN client_timestamp DATETIME NULL', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='checklists' AND COLUMN_NAME='version')=0,
  'ALTER TABLE checklists ADD COLUMN version INT UNSIGNED NOT NULL DEFAULT 1', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- eventos
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='eventos' AND COLUMN_NAME='client_uuid')=0,
  'ALTER TABLE eventos ADD COLUMN client_uuid VARCHAR(80) NULL', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='eventos' AND COLUMN_NAME='client_timestamp')=0,
  'ALTER TABLE eventos ADD COLUMN client_timestamp DATETIME NULL', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='eventos' AND COLUMN_NAME='version')=0,
  'ALTER TABLE eventos ADD COLUMN version INT UNSIGNED NOT NULL DEFAULT 1', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- localizacoes
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='localizacoes' AND COLUMN_NAME='client_uuid')=0,
  'ALTER TABLE localizacoes ADD COLUMN client_uuid VARCHAR(80) NULL', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='localizacoes' AND COLUMN_NAME='client_timestamp')=0,
  'ALTER TABLE localizacoes ADD COLUMN client_timestamp DATETIME NULL', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='localizacoes' AND COLUMN_NAME='version')=0,
  'ALTER TABLE localizacoes ADD COLUMN version INT UNSIGNED NOT NULL DEFAULT 1', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- destinos
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='destinos' AND COLUMN_NAME='client_uuid')=0,
  'ALTER TABLE destinos ADD COLUMN client_uuid VARCHAR(80) NULL', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='destinos' AND COLUMN_NAME='client_timestamp')=0,
  'ALTER TABLE destinos ADD COLUMN client_timestamp DATETIME NULL', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='destinos' AND COLUMN_NAME='version')=0,
  'ALTER TABLE destinos ADD COLUMN version INT UNSIGNED NOT NULL DEFAULT 1', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- Colunas geradas por JSON para consulta rápida sem migrar metadados TEXT para JSON rígido.
-- Usa JSON_VALID para não quebrar registros antigos com metadados inválidos.
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='localizacoes' AND COLUMN_NAME='temperatura_c')=0,
  "ALTER TABLE localizacoes ADD COLUMN temperatura_c DECIMAL(5,2) GENERATED ALWAYS AS (CAST(CASE WHEN JSON_VALID(metadados) THEN JSON_UNQUOTE(JSON_EXTRACT(metadados, '$.temperatura_c')) ELSE NULL END AS DECIMAL(5,2))) VIRTUAL", 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='localizacoes' AND INDEX_NAME='idx_localizacoes_temp')=0,
  'ALTER TABLE localizacoes ADD INDEX idx_localizacoes_temp (temperatura_c)', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='eventos' AND COLUMN_NAME='temp_max_c')=0,
  "ALTER TABLE eventos ADD COLUMN temp_max_c DECIMAL(5,2) GENERATED ALWAYS AS (CAST(CASE WHEN JSON_VALID(metadados) THEN JSON_UNQUOTE(JSON_EXTRACT(metadados, '$.temp_max')) ELSE NULL END AS DECIMAL(5,2))) VIRTUAL", 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='eventos' AND INDEX_NAME='idx_eventos_temp_max')=0,
  'ALTER TABLE eventos ADD INDEX idx_eventos_temp_max (temp_max_c)', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
